### ISSUE TITLE
We should collaborate

### ISSUE THREAD

**Issue by matthewmueller** [hmarr/codecube#1]
Hey man, cool project! I've been working on something similar:

https://github.com/matthewmueller/coderunner

Looks like you solved some of the resource limiting issues that took coderunner.io down. I have implemented dependency installation using volumes, which might be nice for this project.

I'm in the process of pulling out the API so you can simply pass a project directory, specify the language and it will return the output. You could do a lot of interesting things with this like have native editors be clients and whatnot.

**Comment by hmarr** [comment]
Hey - Coderunner looks awesome.

Resource limiting is still the biggest challenge facing CodeCube, it'd be great to work together to solve the problems.

My email address is harry at hmarr dot com - let's chat about how we could help each other out.
